### ISSUE TITLE
Could not register the command method modifyEnchantmentAddCommand

### ISSUE THREAD

**Issue by phyre** [Nunnery/MythicDrops#234]
Hello, 

I've never written a ticket before, - so I'm hoping I did this right!

I loaded up the version available for download on spigotmc, - 4.0.0-b3-STABLE.  I'm running Spigot 1.8.3  

[03:26:34] [Server thread/INFO]: Starting minecraft server version 1.8.3
[03:26:34] [Server thread/INFO]: Loading properties
[03:26:34] [Server thread/INFO]: Default game type: SURVIVAL
[03:26:34] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2f787bd-e4ca2af (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Console is tossing me this error on startup:

[03:26:38] [Server thread/ERROR]: Error occurred while enabling MythicDrops v4.0.0-b3-STABLE (Is it up to date?)
se.ranzdo.bukkit.mythicdrops.methodcommand.RegisterCommandMethodException: Could not register the command method modifyEnchantmentAddCommand in the class com.tealcube.minecraft.bukkit.mythicdrops.commands.MythicDropsCommand. Reason: Could not find a ArgumentHandler for (org.bukkit.enchantments.Enchantment)
	at se.ranzdo.bukkit.mythicdrops.methodcommand.RegisteredCommand.getArgumenHandler(RegisteredCommand.java:130) ~[?:?]
	at se.ranzdo.bukkit.mythicdrops.methodcommand.RegisteredCommand.set(RegisteredCommand.java:293) ~[?:?]
	at se.ranzdo.bukkit.mythicdrops.methodcommand.CommandHandler.registerCommands(CommandHandler.java:218) ~[?:?]
	at com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin.onEnable(MythicDropsPlugin.java:753) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-2f787bd-e4ca2af]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

Please let me know if you need any other information :)

**Comment by Nunnery** [comment]
Ah, right, my bad. I'll have this fixed momentarily.
