### ISSUE TITLE
diamond axe does not spawn

### ISSUE THREAD

**Issue by GreatRaceofGithub** [Nunnery/MythicDrops#315]
<Config>

itemTypes:
  allowedGroups:
  - axe
  disallowedGroups:
  - gold
  - stone
  - iron
  - wood

If you limit only the diamond axe in this manner, you get an error

[20:17:25] [Server thread/INFO]: ()  issued server command: /md spawn -a 1 -t mythic
[20:17:25] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:17:25] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:17:25] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:17:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:17:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:17:25] [Server thread/WARN]: 	at se.ranzdo.bukkit.mythicdrops.methodcommand.RegisteredCommand.executeMethod(RegisteredCommand.java:130)
[20:17:25] [Server thread/WARN]: 	at se.ranzdo.bukkit.mythicdrops.methodcommand.RegisteredCommand.execute(RegisteredCommand.java:87)
[20:17:25] [Server thread/WARN]: 	at se.ranzdo.bukkit.mythicdrops.methodcommand.RegisteredCommand.execute(RegisteredCommand.java:92)
[20:17:25] [Server thread/WARN]: 	at se.ranzdo.bukkit.mythicdrops.methodcommand.CommandHandler.onCommand(CommandHandler.java:272)
[20:17:25] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:17:25] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:17:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:17:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:17:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[20:17:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[20:17:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:17:25] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: bound must be positive
[20:17:25] [Server thread/WARN]: 	at java.util.Random.nextInt(Unknown Source)
[20:17:25] [Server thread/WARN]: 	at org.apache.commons.lang.math.JVMRandom.nextInt(JVMRandom.java:118)
[20:17:25] [Server thread/WARN]: 	at org.apache.commons.lang.math.RandomUtils.nextInt(RandomUtils.java:88)
[20:17:25] [Server thread/WARN]: 	at org.apache.commons.lang.math.RandomUtils.nextInt(RandomUtils.java:74)
[20:17:25] [Server thread/WARN]: 	at com.tealcube.minecraft.bukkit.mythicdrops.utils.ItemUtil.getRandomMaterialFromCollection(ItemUtil.java:49)
[20:17:25] [Server thread/WARN]: 	at com.tealcube.minecraft.bukkit.mythicdrops.items.MythicDropBuilder.build(MythicDropBuilder.java:154)
[20:17:25] [Server thread/WARN]: 	at com.tealcube.minecraft.bukkit.mythicdrops.commands.MythicDropsCommand.spawnSubcommand(MythicDropsCommand.java:132)
[20:17:25] [Server thread/WARN]: 	... 24 more

**Comment by Nunnery** [comment]
If you only want DIAMOND_AXE, just use
```
allowedIds:
- DIAMOND_AXE
```
instead of abusing groups.

I'll hopefully be fixing this soon.

**Comment by Nunnery** [comment]
I've been unable to replicate this with the configuration you mentioned above. Ensure that the axe item group still contains DIAMOND_AXE.
